name: Deploy website on push

on:
  push:
    branches: ["main"]
  # Enables manually triggering of Workflow with file synchronization option
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"

jobs:
  web-deploy:
    name: Deploy Main Branch
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
    
    - name: Sync files
      uses: milanmk/actions-file-deployer@master
      with:
        remote-protocol: "sftp"
        remote-host: ${{ secrets.FTP_SERVER }}
        remote-user: ${{ secrets.FTP_USERNAME }}
        remote-password: ${{ secrets.FTP_PASSWORD }}
        remote-port: 22
        sync-delta-excludes: ".git* web/typescript/**"
        local-path: web/
        remote-path: ${{ secrets.FTP_SERVER_DIRECTORY }}
